# https://taskfile.dev

version: "3"

tasks:
  makemigrations:
    desc: "Make Django DB migrations"
    cmds:
      - uv run --directory=backend python manage.py makemigrations

  sample-data:
    desc: "Load sample data into DB"
    cmds:
      - rm backend/db.sqlite3
      - uv run --directory=backend python manage.py migrate --noinput
      - uv run --directory=backend python manage.py loaddata sample_data.json
    silent: false

  start-backend:
    desc: "Start Django backend server"
    cmds:
      - uv run --directory=backend python manage.py migrate --noinput
      - uv run --directory=backend python manage.py runserver 0.0.0.0:8000
    silent: false
