# https://taskfile.dev

version: "3"

tasks:
  makemigrations:
    desc: "Make Django DB migrations"
    cmds:
      - uv run --directory=backend python manage.py makemigrations

  clear-data:
    desc: "Clear DB"
    cmds:
      - rm backend/db.sqlite3
      - uv run --directory=backend python manage.py migrate --noinput

  sample-data:
    desc: "Load sample data into DB"
    cmds:
      - rm backend/db.sqlite3
      - uv run --directory=backend python manage.py migrate --noinput
      - uv run --directory=backend python manage.py loaddata sample_data.json
    silent: false

  real-data:
    desc: "Load real data into DB"
    cmds:
      - python local/read_sql.py
      - rm backend/db.sqlite3
      - uv run --directory=backend python manage.py migrate --noinput
      - uv run --directory=backend python manage.py loaddata real_data.json
    silent: false

  start-backend:
    desc: "Start Django backend server"
    cmds:
      - uv run --directory=backend python manage.py migrate --noinput
      - uv run --directory=backend python manage.py runserver 0.0.0.0:8000
    silent: false

  start-frontend:
    desc: "Start Vite frontend development server"
    cmds:
      - cd frontend && npm run dev
    silent: false

  test:
    desc: "Run all tests"
    deps:
      - frontend-test
      - backend-test
    silent: false

  backend-test:
    desc: "Run backend tests"
    cmds:
      - cd backend && uv run ruff format
      - cd backend && uv run ruff check --fix
      - cd backend && uv run python manage.py check
      - cd backend && uv run python manage.py test
    silent: false

  frontend-test:
    desc: "Run frontend tests with Vitest"
    cmds:
      - cd frontend && npx vitest --run
    silent: false

  codex:
    desc: "Run Codex"
    cmds:
      - start-codex --project-doc docs/architecture.md
    silent: false
