# Generated by Django 5.2 on 2025-04-17 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActionType",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_column="Name", max_length=10)),
            ],
            options={
                "db_table": "ActionType",
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("name", models.TextField(db_column="Name", null=True)),
                ("isin", models.CharField(db_column="ISIN", max_length=20, null=True)),
                (
                    "short_name",
                    models.CharField(db_column="ShortName", max_length=30, null=True),
                ),
            ],
            options={
                "db_table": "Investment",
            },
        ),
        migrations.CreateModel(
            name="Development",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_column="Date", null=True)),
                (
                    "price",
                    models.DecimalField(
                        db_column="Price", decimal_places=8, max_digits=14, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        db_column="Quantity", decimal_places=8, max_digits=37, null=True
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        db_column="Value", decimal_places=16, max_digits=51, null=True
                    ),
                ),
                (
                    "investment",
                    models.ForeignKey(
                        db_column="InvestmentID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.investment",
                    ),
                ),
            ],
            options={
                "db_table": "Development",
            },
        ),
        migrations.CreateModel(
            name="InvestmentPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_column="Date", null=True)),
                (
                    "price",
                    models.DecimalField(
                        db_column="Price", decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(db_column="Source", max_length=20, null=True),
                ),
                (
                    "investment",
                    models.ForeignKey(
                        db_column="InvestmentID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.investment",
                    ),
                ),
            ],
            options={
                "db_table": "InvestmentPrice",
            },
        ),
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("date", models.DateField(db_column="Date", null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        db_column="Quantity", decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_column="Amount", decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        db_column="Fee", decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        db_column="ActionID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.actiontype",
                    ),
                ),
                (
                    "investment",
                    models.ForeignKey(
                        db_column="InvestmentID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.investment",
                    ),
                ),
            ],
            options={
                "db_table": "Movement",
            },
        ),
    ]
