# Generated by Django 5.2 on 2025-04-18 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="investment",
            old_name="short_name",
            new_name="shortname",
        ),
    ]
