# Generated by Django 5.2 on 2025-04-18 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_load_actiontypes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Development",
            new_name="PrecalculatedDevelopment",
        ),
        migrations.AlterModelTable(
            name="precalculateddevelopment",
            table="PrecalculatedDevelopment",
        ),
    ]
