# Generated by Django 5.2 on 2025-11-06 22:43

from django.db import migrations, models


def create_initial_settings(apps, schema_editor):
    Settings = apps.get_model("core", "Settings")
    if not Settings.objects.exists():
        Settings.objects.create(base_currency="EUR")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_short_name_investment_shortname"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "base_currency",
                    models.CharField(db_column="BaseCurrency", default="EUR", max_length=3),
                ),
            ],
            options={
                "db_table": "Settings",
            },
        ),
        migrations.AddField(
            model_name="investment",
            name="quote_provider",
            field=models.CharField(db_column="QuoteProvider", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="investment",
            name="ticker_symbol",
            field=models.CharField(db_column="TickerSymbol", max_length=20, null=True),
        ),
        migrations.RunPython(create_initial_settings),
    ]
